<link rel="stylesheet" href="<?php echo base_url();?>assets/css/style.default.css" type="text/css" />
<link rel="stylesheet" href="<?php echo base_url();?>assets/css/style.shinyblue.css" type="text/css" />
<!--<link rel="stylesheet" href="<?php echo base_url();?>assets/css/bootstrap.min.css" type="text/css" />-->
<link rel="stylesheet" href="<?php echo base_url();?>assets/css/bootstrap-fileupload.min.css" type="text/css" />
<link rel="stylesheet" href="<?php echo base_url();?>assets/css/bootstrap-timepicker.min.css" type="text/css" />
<link rel="stylesheet" href="<?php echo base_url();?>assets/css/datepicker.css" type="text/css" />
<link rel="stylesheet" href="<?php echo base_url();?>assets/css/select2.css" type="text/css" />
<!--<link rel="stylesheet" href="<?php echo base_url();?>assets/DataTables/media/css/jquery.dataTables.min.css" type="text/css" />-->
<!--<link rel="stylesheet" href="<?php echo base_url();?>assets/DataTables/media/css/dataTables.bootstrap.css" type="text/css" />-->