<script type="text/javascript" src="<?php echo base_url();?>assets/js/jquery-1.9.1.min.js"></script>
<script type="text/javascript" src="<?php echo base_url();?>assets/js/jquery-migrate-1.1.1.min.js"></script>
<script type="text/javascript" src="<?php echo base_url();?>assets/js/jquery-ui-1.9.2.min.js"></script>
<script type="text/javascript" src="<?php echo base_url();?>assets/js/bootstrap3.min.js"></script>
<script type="text/javascript" src="<?php echo base_url();?>assets/js/bootstrap-fileupload.min.js"></script>
<script type="text/javascript" src="<?php echo base_url();?>assets/js/bootstrap-timepicker.min.js"></script>
<script type="text/javascript" src="<?php echo base_url();?>assets/js/bootstrap-datepicker.js"></script>
<script type="text/javascript" src="<?php echo base_url();?>assets/js/jquery.uniform.min.js"></script>
<script type="text/javascript" src="<?php echo base_url();?>assets/js/jquery.validate.min.js"></script>
<script type="text/javascript" src="<?php echo base_url();?>assets/js/jquery.tagsinput.min.js"></script>
<script type="text/javascript" src="<?php echo base_url();?>assets/js/jquery.autogrow-textarea.js"></script>
<script type="text/javascript" src="<?php echo base_url();?>assets/DataTables/media/js/jquery.dataTables.min.js"></script>
<!--<script type="text/javascript" src="<?php echo base_url();?>assets/DataTables/media/js/dataTables.bootstrap.min.js"></script>-->
<!--<script type="text/javascript" src="<?php echo base_url();?>assets/js/jquery.dataTables.1.10.min.js"></script>-->
<script type="text/javascript" src="<?php echo base_url();?>assets/js/jquery.alerts.js"></script>
<script type="text/javascript" src="<?php echo base_url();?>assets/js/charCount.js"></script>
<script type="text/javascript" src="<?php echo base_url();?>assets/js/colorpicker.js"></script>
<script type="text/javascript" src="<?php echo base_url();?>assets/js/ui.spinner.min.js"></script>
<script type="text/javascript" src="<?php echo base_url();?>assets/js/chosen.jquery.min.js"></script>
<script type="text/javascript" src="<?php echo base_url();?>assets/js/jquery.cookie.js"></script>
<script type="text/javascript" src="<?php echo base_url();?>assets/js/modernizr.min.js"></script>
<script type="text/javascript" src="<?php echo base_url();?>assets/js/custom.js"></script>
<script type="text/javascript" src="<?php echo base_url();?>assets/js/forms.js"></script>
<script type="text/javascript" src="<?php echo base_url();?>assets/js/responsive-tables.js"></script>
<script type="text/javascript" src="<?php echo base_url();?>assets/js/select2.js"></script>
<script type="text/javascript" src="<?php echo base_url();?>assets/js/jquery.form.js"></script>
<script type="text/javascript" src="<?php echo base_url();?>assets/js/jquery.uploadfile.js"></script>
<!--[if lte IE 8]><script language="javascript" type="text/javascript" src="js/excanvas.min.js"></script><![endif]-->